### ISSUE TITLE
install.sh should install the repo file

### ISSUE THREAD

**Issue by ksens** [Paradigm4/extra-scidb-libs#16]
@rvernica 

Currently extra-scidb-libs ships extra-scidb-libs via the following command

```sh
yum install --assumeyes \
            https://paradigm4.github.io/extra-scidb-libs/extra-scidb-libs-18.1-$PKG_VER-1.x86_64.rpm
```

Can you change the script so that the default behavior is as follows:

## 1. Install the following repo file onto the system

```sh
cat /etc/yum.repos.d/paradigm4-extra.repo

[paradigm4-extra]
name=Paradigm4 extra libs repository
baseurl=https://downloads.paradigm4.com/extra/18.1/centos6.3/
enabled=0
fastestmirror_enabled=0
gpgcheck=0
skip_if_unavailable=1
```

## 2. Install extra-scidb-libs using yum

```sh
yum install --enablerepo=paradigm4-extra extra-scidb-libs-18.1
# Latest version would be installed
```

# Extra flag

You can provide an extra flag e.g. `--dev` which would trigger download from `paradigm4.github.io` -- path to be used only for development

**Comment by rvernica** [comment]
Fixed in the latest release [v18.1.4](https://github.com/Paradigm4/extra-scidb-libs/releases/tag/v18.1.4)
* Added SciDB Extra Libs repository
* Install extra-scidb-libs from there. Apache Arrow dependency will be picked up and installed from there automatically
* The script has `--github` flag to install packages from GtiHub.com. See [install.sh](https://github.com/Paradigm4/extra-scidb-libs/blob/master/install.sh) for details.
* Added manual installation steps as well in [README](https://paradigm4.github.io/extra-scidb-libs/)
