### ISSUE TITLE
Need CHANGELOG for extra scidb libs 19.3-3

### ISSUE THREAD

**Issue by ksens** [Paradigm4/extra-scidb-libs#25]
https://paradigm4.github.io/extra-scidb-libs/#scidb-193-1

@rvernica Can you please add the changelog for extra scidb libs version 19.3-3. Thanks in advance.

**Comment by rvernica** [comment]
The latest "GitHub" release was `19.3.2`. Since that release it looks like there was only one commit made in the [master](https://github.com/Paradigm4/extra-scidb-libs/commits/master) and two commits in the [v19.11](https://github.com/Paradigm4/extra-scidb-libs/commits/v19.11) branch.

I'm not sure how `19.3.3` was built but if this is for SciDB `19.3` then it should have been build from the master.

**Comment by ksens** [comment]
@martin-resnick could you take a look at this?

**Comment by rvernica** [comment]
Fixed in 09a1e0606f96d3d2d9961ca45cfa6f6015cac274 and d5f6d86c6028121aa0cef62b0b2def71c8080934
