### ISSUE TITLE
Check the upgrade scenario

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/extra-scidb-libs#3]
When the shim package is already installed, this doesn't install cleanly. 
I was upgrading from 17.x and somehow ended up with shim being installed to /opt/scidb/16.9. It worked after I erased /opt/scidb/16.9 and /opt/scidb/17.1

**Comment by rvernica** [comment]
When the package is built, it uses `SCIDB_VER` and `SCIDB_INSTALL_PATH` environment variables to determine where to put the installed files. So, it the package is built on `18.1`, it should install the files in the right `18.1` path. If you have multiple installations, check the values of these environment variables. Re-open the ticket if the issue is still present.
