### ISSUE TITLE
20.10 version does not seem to have bridge

### ISSUE THREAD

**Issue by ksens** [Paradigm4/extra-scidb-libs#36]
@JAKinchen @rvernica 

The 20.10 version of extra-scidb-libs does not seem to have the `bridge` library. Can one of you please help with this? Thanks. 

I am in the process of deploying scidb 20.10 at a couple of servers, and would like to use `bridge`. 

```sh
yum list installed | grep extra-scidb-libs-20.10
# extra-scidb-libs-20.10.x86_64         1-1                        @scidb-extra

iquery -aq "load_library('bridge')"
# SystemException in file: src/util/PluginManager.cpp function: findModule line: 114 instance: s0-i0 (0)
# Error id: scidb::SCIDB_SE_PLUGIN_MGR::SCIDB_LE_CANT_LOAD_MODULE
# Error description: Plugin manager error. Cannot load module '/opt/scidb/20.10/lib/scidb/plugins/libbridge.so', dlopen 
# returned '/opt/scidb/20.10/lib/scidb/plugins/libbridge.so: cannot open shared object file: No such file or directory'.
```

**Comment by rvernica** [comment]
I would need to build Docker images for SciDB 20.10 in order to build extra-scidb-libs packages.

An alternative might be to have Bridge compiled on a SciDB 20.10 instalation and copy over libbridge.so. Bridge README contains instructions on how to build its dependencies (Arrow and AWS SDK). As a side note, we are in the final testing phase of upgrading the AWS SDK version used in Bridge to 1.9.97.

**Comment by ksens** [comment]
@rvernica 

I figured out a workaround for now, and am not using bridge on the 20.10 installation right now. Yes, I could build bridge for scidb 20.10 if needed.

PS: In terms of Docker -- I propose that you can skip 20.10 Docker work altogether, but do it when scidb 21.8 comes out. I believe I am the only one using scidb 20.10 on customer installations, and I hope to upgrade to 21.8 as soon as it comes out.
