### ISSUE TITLE
Maybe: use arrow-less aio_tools

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/extra-scidb-libs#5]
Installing this with arrow is a bit convoluted. Maybe, for now, we can have a branch of  accelerated_io_tools without arrow? That is - make a branch aio v18.1. Put aio v18.1 in this package. Keep working on arrow changes in master.
@ksens @rvernica your thoughts?

**Comment by ksens** [comment]
@CarlsonP4 had warned us about this before.

The bigger issue here is that we do not have a good release tagging mechanism for our plugins. 

Here is my proposal to fix this issue:
 
- We currently have branches relating to different SciDB versions (`v18.1`, `v16.9`, ...). We continue to have this strategy. 
- Separately I propose that we start adding tags to specific commits as release candidates (`rel18.1.1`, `rel18.1.2` ...)

This way, work related to a SciDB version can happen on any branch. But the tags would really show what are release candidates. And the release `tag` is what we should provide as input to `extra-scidb-libs` so that there is an exact correspondence between a version of `extra-scidb-libs` and plugin versions. 

Like any process improvement effort, this will take some implementation time in the short-term but will give gains in the long term.

@rvernica
I found [this commit](https://github.com/Paradigm4/accelerated_io_tools/commit/94632d960e8404cd39eb08a3285757320e12aacc) to be the last one on master before you started the arrow integration work. Can you confirm this. I have tagged this as `rel18.1.1`.

**Comment by rvernica** [comment]
That is the right commit for `accelerated_io_tools`.

**Comment by rvernica** [comment]
Version `1` of the package includes older `accelerated_io_tools` without Apache Arrow, while version `2` of the package includes `accelerated_io_tools` with Apache Arrow. The two versions are available [here](https://paradigm4.github.io/extra-scidb-libs/). Also the `install.sh` script available on the same page facilitates the dependency installation (including Apache Arrow) and installs the latest version of the package.
