### ISSUE TITLE
Superfunpack needs libpcre, not installed by default

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/extra-scidb-libs#7]
After installing as shown here: https://paradigm4.github.io/scidblog/scidb-installation/

```
$ iquery -aq "load_library('superfunpack')"
SystemException in file: src/util/PluginManager.cpp function: findModule line: 106
Error id: scidb::SCIDB_SE_PLUGIN_MGR::SCIDB_LE_CANT_LOAD_MODULE
Error description: Plugin manager error. Cannot load module '/opt/scidb/18.1/lib/scidb/plugins/libsuperfunpack.so', dlopen returned 'libpcre.so.0: cannot open shared object file: No such file or directory'.
```

**Comment by rvernica** [comment]
Two comments about this:
1. Interesting that you have a system without `libpcre`. I tried to remove the `pcre` library from both Debian and CentOS systems it is not easy. Both `dpkg` and `yum` depend on it.
1. In order to compile `superfunpack` you need the `pcre` include files, but it does not need to link against `libpcre`. See this [PR.](https://github.com/Paradigm4/superfunpack/pull/6) Interesting how it needs it at runtime.

**Comment by rvernica** [comment]
I was able to reproduce this on CentOS 7. CentOS 7 has `libpcre.so.1` and `superfunpack` is linked against `libpcre.so.0`.

To fix this, I built the `extra-scidb-libs` package in CentOS 6 using the `remove-pcre-flag` branch of `superfunpack`. I installed the resulting package on CentOS 7 and it works:
```
> iquery -aq "load_library('superfunpack')"
Query was executed successfully
```

**Comment by rvernica** [comment]
Verified `rsub` works in CentOS 7:
```bash
> iquery -aq "apply(build(<s:string>[i=0:0,1,0],'{0}[(\'Paul Brown is a serious serious man.\')]',true), r, rsub(s,'s/serious/silly/'))"
{i} s,r
{0} 'Paul Brown is a serious serious man.','Paul Brown is a silly serious man.'
[```

**Comment by rvernica** [comment]
The [PR](https://github.com/Paradigm4/superfunpack/pull/6) for superfunpack has been merged and the latest release of superfunpack is used in extra-scidb-libs. This should be fixed now.
